# Generated by Django 5.0.4 on 2024-04-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='publisher',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
