# Generated by Django 5.0.4 on 2024-04-11 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookmodel_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='ISBN',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
