# Generated by Django 5.0.4 on 2024-04-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_bookmodel_isbn_alter_bookmodel_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'ordering': ['id']},
        ),
    ]
