# Generated by Django 5.0.4 on 2024-04-11 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_bookmodel_author_alter_bookmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z{1, 100}]$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z{1, 100}]$', 'Min 2 max 100 characters')]),
        ),
    ]
