# Generated by Django 5.0.4 on 2024-04-12 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_bookmodel_isbn_alter_bookmodel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='ISBN',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\d\\-]{10,20}$', 'min 10 max 20 characters')]),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^\\S+(\\s+\\S+){1,99}$', 'Only alphabetical characters are allowed, min 2 max 100 characters')]),
        ),
    ]
