# Generated by Django 5.0.4 on 2024-04-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_bookmodel_isbn_alter_bookmodel_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='publisher',
            new_name='published',
        ),
    ]
